# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<BOOTSTRAP
apt-get update -qq
[ -x /usr/bin/git ] || apt-get install -y -q git
[ -x /usr/bin/make ] || apt-get install -y -q make
gem list r10k -i 1>/dev/null || gem install --quiet --no-rdoc --no-ri r10k 1>/dev/null
cd /vagrant && r10k -v info puppetfile install
BOOTSTRAP

Vagrant.configure("2") do |config|

  # Ubuntu
  config.vm.define "trusty64" do |c|
    c.vm.box = "ubuntu/trusty64"

    c.vm.provision :shell, inline: $script
    c.vm.provision :puppet do |puppet|
      puppet.module_path = "modules"
    end
  end

end
