source 'https://rubygems.org'

gem 'rake'
gem 'rack', '2.1.4'
gem 'inspec', '~> 5'
gem 'rubocop', '~> 0.93.0'
gem 'highline', '~> 2.1.0'

group :integration do
  gem 'berkshelf'
  gem 'kitchen-inspec'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
