source 'https://rubygems.org'

gem 'rake'
gem 'rack', '3.1.6'
gem 'inspec', '~> 6'
gem 'rubocop', '~> 1.65.0'
gem 'highline', '~> 2.1.0'

group :integration do
  gem 'berkshelf'
  gem 'kitchen-inspec'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
