# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Ubuntu
  config.vm.define "ubuntu-trusty" do |c|
    c.vm.box = "ubuntu/trusty64"
    c.vm.network :private_network, ip: "192.168.33.44"

    c.vm.provision :shell, inline: "apt-get update"
	c.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "default.yml"
      ansible.install_mode = "pip"
      ansible.version = "2.2.1.0"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.sudo = true
    end
  end

end
