source 'https://rubygems.org'

gem 'rake'
gem 'rack', '1.6.4'
gem 'inspec', '~> 1'
gem 'rubocop', '~> 0.93.0'
gem 'highline', '~> 1.6.0'

group :integration do
  gem 'berkshelf'
  gem 'kitchen-inspec'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
