# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Ubuntu
  config.vm.define "ubuntu-trusty" do |c|
    c.vm.box = "ubuntu/trusty64"
    c.vm.network :private_network, ip: "192.168.33.44"

    c.vm.provision :shell, inline: "apt-get update"
    c.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.sudo = true
    end
  end

end
